minimumReleaseAge: 10080
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
shellEmulator: true

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
